name: 'projet8'
version: '1.0.0'

profile: 'projet8'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

dbt-cloud:
  project-id: "70506183143250"
  defer-env-id: null

models:
  projet8:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    mart:
      +materialized: table
      +schema: mart
